### PR TITLE
Upgrade ember weakmap to 3.0

### PR DESCRIPTION
**Pull request by ryanto**
WeakMap is now on the Ember object. See here: https://github.com/thoov/ember-weakmap#usage

### CODE REVIEW

**Comment by workmanw** [comment]
@ryanto Isn't this just in time for everyone to stop using the `Ember` namespace? Hehe. I'm actually wonder polyfills will looks like in the future where no one uses the `Ember` namespace.

**Comment by ryanto** [comment]
No idea! Reason for this PR is it clashes with ember macro helpers, which other addons like ember moment depend on.

https://github.com/kellyselden/ember-macro-helpers/blob/master/package.json#L26

@thoov do you have any input?

**Comment by workmanw** [comment]
@ryanto Well I have no objection to this, it was more of a curiosity.

**Comment by thoov** [comment]
@workmanw @ryanto I had the same question about the namespacing concern which I brought up with here: https://github.com/stefanpenner/ember-state-services/pull/76. You can read what Robert said but the TLDR is that it is still TBD. This is one area I will be looking into over the next few weeks as to what should be the correct way of import polyfills in this new import world we live in.

**Comment by workmanw** [comment]
@thoov 👍 thanks for providing that. I maintain a polyfill also, so it was more of curiosity for me than for this addon consuming another.

**Pull request merged**
