### PR TITLE
Release 0.2.1

### PR DESCRIPTION
**Pull request by workmanw**

### CODE REVIEW

**Comment by workmanw** [comment]
UGH. I'm getting some weird error all of a sudden that I dont' have time to dig into:

> [0112/122100.255715:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I\'m aborting now. You need to make sure that /opt/google/chrome/chrome-sandbox is owned by root and has mode 4755.\nFailed to generate minidump.


Anyone seen this? I don't see anything different about this commit. Just trying to release a new version.

**Comment by seansellek** [comment]
I have seen this on other projects as well. I don't have a solution yet but I am looking into it. Seems to be an environment issue with Travis CI.

**Comment by workmanw** [comment]
@seansellek Thanks. What's puzzling is that it just work on the last PR I merge yesterday. Then just a few hours later it stopped working when I tried to cut a new release.

**Comment by seansellek** [comment]
Update: It's a known issue with Travis CI https://github.com/travis-ci/travis-ci/issues/8836

A couple workarounds:
1. Use sudo

```yml
# travis.yml
sudo: required
addons:
 chrome: stable
```

2. use Firefox:

```yml
# travis.yml
addons:
    firefox: 57.0
```

What's strange is that it looks like the issue is closed, but clearly it's popped up again.

**Comment by workmanw** [comment]
@seansellek That did the trick. Let's get this release cut. Thanks for your help.

**Pull request merged**
